// soal.js
const quizData = {
    sejarah: [
        { q: "Siapa Presiden pertama Indonesia?", options: ["Hatta", "Soekarno", "Soeharto", "Habibie"], correct: 1 },
        { q: "Tahun berapa Indonesia merdeka?", options: ["1945", "1944", "1946", "1947"], correct: 0 },
        { q: "Lagu Indonesia Raya diciptakan oleh...", options: ["Ibu Sud", "Kusbini", "W.R. Supratman", "C. Simanjuntak"], correct: 2 },
        { q: "Sumpah Pemuda terjadi pada tanggal...", options: ["28 Oktober 1928", "17 Agustus 1945", "1 Juni 1945", "10 November 1945"], correct: 0 },
        { q: "Pahlawan yang dijuluki 'Ayam Jantan dari Timur' adalah...", options: ["Pattimura", "Sultan Hasanuddin", "Diponegoro", "Tuanku Imam Bonjol"], correct: 1 },
        { q: "Kerajaan Hindu tertua di Indonesia adalah...", options: ["Majapahit", "Tarumanegara", "Kutai", "Sriwijaya"], correct: 2 },
        { q: "Teks Proklamasi diketik oleh...", options: ["Sayuti Melik", "Sukarni", "Wikana", "Latif Hendraningrat"], correct: 0 },
        { q: "Belanda pertama kali mendarat di Indonesia di daerah...", options: ["Jakarta", "Surabaya", "Banten", "Maluku"], correct: 2 },
        { q: "Peristiwa Rengasdengklok adalah penculikan terhadap...", options: ["Hatta & Syahrir", "Soekarno & Hatta", "Soeharto", "Sudirman"], correct: 1 },
        { q: "BPUPKI diketuai oleh...", options: ["Dr. Radjiman Wedyodiningrat", "Ir. Soekarno", "Moh. Hatta", "Ki Hajar Dewantara"], correct: 0 },
        { q: "Kerajaan Islam pertama di Indonesia adalah...", options: ["Demak", "Samudera Pasai", "Mataram", "Aceh"], correct: 1 },
        { q: "Siapa penjahit bendera Pusaka Merah Putih?", options: ["Cut Nyak Dien", "Ibu Fatmawati", "Kartini", "Dewi Sartika"], correct: 1 },
        { q: "Kota tempat dijatuhkannya bom atom pertama di Jepang adalah...", options: ["Tokyo", "Nagasaki", "Hiroshima", "Osaka"], correct: 2 },
        { q: "Candi Borobudur dibangun pada masa dinasti...", options: ["Sanjaya", "Syailendra", "Isyana", "Majapahit"], correct: 1 },
        { q: "Pemimpin perlawanan rakyat Maluku terhadap Belanda adalah...", options: ["Pattimura", "Antasari", "Diponegoro", "Imam Bonjol"], correct: 0 },
        { q: "Hari Kebangkitan Nasional diperingati setiap tanggal...", options: ["2 Mei", "20 Mei", "1 Juni", "10 November"], correct: 1 },
        { q: "Perang Diponegoro terjadi pada tahun...", options: ["1825-1830", "1945-1949", "1908-1928", "1602-1605"], correct: 0 },
        { q: "Ibu kota RI pernah dipindahkan ke Yogyakarta pada tahun...", options: ["1945", "1946", "1948", "1950"], correct: 1 },
        { q: "Gajah Mada adalah patih terkenal dari kerajaan...", options: ["Singasari", "Kediri", "Majapahit", "Pajajaran"], correct: 2 },
        { q: "Konferensi Asia Afrika (KAA) pertama dilaksanakan di kota...", options: ["Jakarta", "Surabaya", "Bandung", "Medan"], correct: 2 },
        { q: "Organisasi Budi Utomo didirikan pada tahun...", options: ["1908", "1928", "1945", "1998"], correct: 0 },
        { q: "Pendiri organisasi Muhammadiyah adalah...", options: ["Hasyim Asy'ari", "Ahmad Dahlan", "Agus Salim", "Samanhudi"], correct: 1 },
        { q: "Siapa yang membacakan teks Proklamasi?", options: ["Moh. Hatta", "Soekarno", "Sutan Syahrir", "Ahmad Soebardjo"], correct: 1 },
        { q: "VOC dibubarkan pada tahun...", options: ["1799", "1800", "1602", "1942"], correct: 0 },
        { q: "Nama asli Pangeran Diponegoro adalah...", options: ["Raden Mas Ontowiryo", "Raden Patah", "Raden Said", "Raden Wijaya"], correct: 0 },
        { q: "Jepang menyerah tanpa syarat kepada sekutu pada...", options: ["14 Agustus 1945", "17 Agustus 1945", "10 November 1945", "1 Juni 1945"], correct: 0 },
        { q: "Siapa yang menjabat sebagai Wakil Presiden pertama?", options: ["Adam Malik", "Moh. Hatta", "Hamengkubuwono IX", "BJ Habibie"], correct: 1 },
        { q: "Kerajaan Sriwijaya berpusat di daerah...", options: ["Jambi", "Riau", "Palembang", "Lampung"], correct: 2 },
        { q: "Tokoh yang mendapat julukan Bapak Pendidikan Nasional...", options: ["Ki Hajar Dewantara", "Douwes Dekker", "Cipto Mangunkusumo", "Bung Tomo"], correct: 0 },
        { q: "Ibu kota penjajahan Belanda di Indonesia adalah...", options: ["Bandung", "Batavia", "Surabaya", "Semarang"], correct: 1 },
        { q: "Laksamana yang menyediakan rumahnya untuk perumusan Proklamasi...", options: ["Maeda", "Yamamoto", "Hirohito", "Nagano"], correct: 0 },
        { q: "Sultan Ageng Tirtayasa berasal dari kerajaan...", options: ["Mataram", "Banten", "Gowa", "Ternate"], correct: 1 },
        { q: "Perjanjian Linggarjati ditandatangani pada tahun...", options: ["1945", "1946", "1947", "1948"], correct: 1 },
        { q: "Tokoh emansipasi wanita Indonesia adalah...", options: ["Cut Nyak Dien", "R.A. Kartini", "Martha Christina", "Nyi Ageng Serang"], correct: 1 },
        { q: "Serangan Umum 1 Maret 1949 terjadi di kota...", options: ["Solo", "Yogyakarta", "Semarang", "Magelang"], correct: 1 },
        { q: "Dekrit Presiden dikeluarkan pada tanggal...", options: ["5 Juli 1959", "11 Maret 1966", "21 Mei 1998", "17 Agustus 1945"], correct: 0 },
        { q: "Pencetus Politik Etis adalah...", options: ["Van Deventer", "Daendels", "Raffles", "Van den Bosch"], correct: 0 },
        { q: "Sistem Tanam Paksa disebut juga dengan...", options: ["Landrent", "Cultuurstelsel", "Romusha", "Devide et Impera"], correct: 1 },
        { q: "Prasasti Ciaruteun adalah peninggalan kerajaan...", options: ["Kutai", "Tarumanegara", "Pajajaran", "Holing"], correct: 1 },
        { q: "Perang Padri terjadi di daerah...", options: ["Sumatera Utara", "Sumatera Barat", "Aceh", "Riau"], correct: 1 },
        { q: "Siapa Panglima Besar TNI yang pertama?", options: ["Jenderal Sudirman", "Ahmad Yani", "Nasution", "Suharto"], correct: 0 },
        { q: "Organisasi Islam Nahdlatul Ulama (NU) didirikan oleh...", options: ["Ahmad Dahlan", "Hasyim Asy'ari", "Agus Salim", "Samanhudi"], correct: 1 },
        { q: "Indische Partij didirikan oleh Tiga Serangkai, kecuali...", options: ["Douwes Dekker", "Ki Hajar Dewantara", "Cipto Mangunkusumo", "Moh. Hatta"], correct: 3 },
        { q: "Tugas utama Daendels di Indonesia adalah...", options: ["Membangun sekolah", "Mempertahankan Jawa dari Inggris", "Membangun pelabuhan", "Menanam kopi"], correct: 1 },
        { q: "Raja terkenal dari kerajaan Singasari adalah...", options: ["Ken Arok", "Kertanegara", "Raden Wijaya", "Hayam Wuruk"], correct: 1 },
        { q: "Pemberontakan G30S terjadi pada tahun...", options: ["1945", "1965", "1998", "1950"], correct: 1 },
        { q: "Zaman es berakhir sekitar...", options: ["10.000 SM", "5.000 SM", "1.000 SM", "20.000 SM"], correct: 0 },
        { q: "Siapa pencetus Sumpah Palapa?", options: ["Hayam Wuruk", "Gajah Mada", "Ken Arok", "Raden Patah"], correct: 1 },
        { q: "Kerajaan Maritim terbesar di Indonesia adalah...", options: ["Majapahit", "Singasari", "Sriwijaya", "Demak"], correct: 2 },
        { q: "Sultan Hasanuddin adalah penguasa dari kerajaan...", options: ["Ternate", "Tidore", "Gowa-Tallo", "Bone"], correct: 2 }
    ],
    sains: [
        { q: "Planet terdekat dari Matahari adalah...", options: ["Mars", "Venus", "Merkurius", "Jupiter"], correct: 2 },
        { q: "Zat hijau daun disebut juga...", options: ["Klorofil", "Stomata", "Fotosintesis", "Kambium"], correct: 0 },
        { q: "Gas yang kita hirup saat bernapas adalah...", options: ["Nitrogen", "Oksigen", "Karbon Dioksida", "Hidrogen"], correct: 1 },
        { q: "Penyusun terkecil makhluk hidup adalah...", options: ["Jaringan", "Organ", "Sel", "Sistem"], correct: 2 },
        { q: "H2O adalah rumus kimia untuk...", options: ["Garam", "Udara", "Asam", "Air"], correct: 3 },
        { q: "Benda langit yang mengeluarkan cahaya sendiri adalah...", options: ["Planet", "Bulan", "Meteor", "Bintang"], correct: 3 },
        { q: "Gaya yang menarik benda ke bumi adalah...", options: ["Gaya Magnet", "Gaya Gesek", "Gaya Gravitasi", "Gaya Pegas"], correct: 2 },
        { q: "Pusat Tata Surya kita adalah...", options: ["Bumi", "Matahari", "Jupiter", "Bulan"], correct: 1 },
        { q: "Alat pengukur gempa bumi disebut...", options: ["Seismograf", "Barometer", "Termometer", "Anemometer"], correct: 0 },
        { q: "Perubahan benda dari padat menjadi gas disebut...", options: ["Mencair", "Menguap", "Menyublim", "Membeku"], correct: 2 },
        { q: "Mamalia yang hidup di air adalah...", options: ["Hiu", "Paus", "Penyu", "Gurita"], correct: 1 },
        { q: "Proses pembuatan makanan pada tumbuhan disebut...", options: ["Metamorfosis", "Fotosintesis", "Penyerbukan", "Pernapasan"], correct: 1 },
        { q: "Planet terbesar di Tata Surya kita adalah...", options: ["Saturnus", "Neptunus", "Jupiter", "Bumi"], correct: 2 },
        { q: "Berapa jumlah tulang pada manusia dewasa?", options: ["106", "206", "306", "406"], correct: 1 },
        { q: "Satuan daya listrik adalah...", options: ["Volt", "Ampere", "Ohm", "Watt"], correct: 3 },
        { q: "Zat cair yang mengisi termometer biasanya adalah...", options: ["Air", "Minyak", "Alkohol atau Raksa", "Cuka"], correct: 2 },
        { q: "Energi utama di bumi berasal dari...", options: ["Angin", "Air", "Batu Bara", "Matahari"], correct: 3 },
        { q: "Logam yang berwujud cair pada suhu ruang adalah...", options: ["Besi", "Emas", "Raksa", "Perak"], correct: 2 },
        { q: "Tulang belakang disebut juga...", options: ["Femur", "Vertebra", "Radius", "Ulna"], correct: 1 },
        { q: "Planet merah adalah julukan untuk...", options: ["Venus", "Mars", "Merkurius", "Saturnus"], correct: 1 },
        { q: "Hubungan timbal balik antara makhluk hidup dan lingkungannya disebut...", options: ["Ekosistem", "Habitat", "Populasi", "Komunitas"], correct: 0 },
        { q: "Zat yang memberikan rasa manis alami pada buah adalah...", options: ["Glukosa", "Fruktosa", "Laktosa", "Maltosa"], correct: 1 },
        { q: "Suhu air mendidih pada tekanan normal adalah...", options: ["90 C", "100 C", "110 C", "120 C"], correct: 1 },
        { q: "Hewan pemakan daging disebut...", options: ["Herbivora", "Karnivora", "Omnivora", "Insektivora"], correct: 1 },
        { q: "Cermin yang permukaannya melengkung ke dalam adalah...", options: ["Cermin Datar", "Cermin Cembung", "Cermin Cekung", "Lensa"], correct: 2 },
        { q: "Bagian mata yang mengatur cahaya masuk adalah...", options: ["Retina", "Pupil", "Lensa", "Kornea"], correct: 1 },
        { q: "Vitamin yang banyak terdapat pada jeruk adalah...", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 2 },
        { q: "Kecepatan cahaya sekitar...", options: ["300.000 km/s", "100.000 km/s", "500.000 km/s", "1.000 km/s"], correct: 0 },
        { q: "Zat yang menyebabkan lapisan ozon berlubang adalah...", options: ["CO2", "CFC", "O2", "CH4"], correct: 1 },
        { q: "Pencernaan kimiawi pertama kali terjadi di...", options: ["Lambung", "Mulut", "Usus Halus", "Kerongkongan"], correct: 1 },
        { q: "Bapak Biologi dunia adalah...", options: ["Isaac Newton", "Charles Darwin", "Albert Einstein", "Louis Pasteur"], correct: 1 },
        { q: "Batu yang berasal dari lava yang mendingin adalah...", options: ["Batu Sedimen", "Batu Beku", "Batu Metamorf", "Batu Apung"], correct: 1 },
        { q: "Lampu pijar ditemukan oleh...", options: ["Nikola Tesla", "Alexander Graham Bell", "Thomas Alva Edison", "James Watt"], correct: 2 },
        { q: "Satuan frekuensi adalah...", options: ["Hertz", "Joule", "Newton", "Pascal"], correct: 0 },
        { q: "Kekurangan sel darah merah disebut...", options: ["Leukimia", "Anemia", "Hipertensi", "Hipotensi"], correct: 1 },
        { q: "Golongan darah yang disebut donor universal adalah...", options: ["A", "B", "AB", "O"], correct: 3 },
        { q: "Gaya tarik-menarik antara molekul sejenis disebut...", options: ["Adhesi", "Kohesi", "Kapilaritas", "Tegangan"], correct: 1 },
        { q: "Berapa jumlah planet di Tata Surya kita?", options: ["7", "8", "9", "10"], correct: 1 },
        { q: "Bakteri berbentuk batang disebut...", options: ["Kokus", "Basil", "Spiral", "Vibrio"], correct: 1 },
        { q: "Tulang keras disebut juga...", options: ["Kartilago", "Osteon", "Ligamen", "Tendon"], correct: 1 },
        { q: "Cahaya merambat secara...", options: ["Berbelok", "Lurus", "Melingkar", "Acak"], correct: 1 },
        { q: "Penyakit akibat kurang Vitamin D adalah...", options: ["Sariawan", "Rakitis", "Rabun Senja", "Beri-beri"], correct: 1 },
        { q: "Asam lambung disebut juga...", options: ["H2SO4", "HCl", "NaOH", "CH3COOH"], correct: 1 },
        { q: "Ilmu yang mempelajari tentang jamur adalah...", options: ["Zoologi", "Mikologi", "Botani", "Fisika"], correct: 1 },
        { q: "Gaya yang dihasilkan oleh magnet disebut...", options: ["Gaya Otot", "Gaya Magnet", "Gaya Listrik", "Gaya Gesek"], correct: 1 },
        { q: "Bagian sel yang berfungsi sebagai pusat kendali adalah...", options: ["Sitoplasma", "Mitokondria", "Nukleus", "Ribosom"], correct: 2 },
        { q: "Bunyi tidak dapat merambat melalui...", options: ["Udara", "Air", "Besi", "Ruang Hampa"], correct: 3 },
        { q: "Perubahan kimia contohnya adalah...", options: ["Es mencair", "Kertas terbakar", "Gula larut", "Air menguap"], correct: 1 },
        { q: "Logam yang paling baik menghantarkan listrik adalah...", options: ["Tembaga", "Perak", "Emas", "Aluminium"], correct: 1 },
        { q: "Zat sisa pernapasan manusia adalah...", options: ["Oksigen", "Karbon Dioksida", "Nitrogen", "Hidrogen"], correct: 1 }
    ],
    geografi: [
        { q: "Negara terluas di dunia adalah...", options: ["Kanada", "Tiongkok", "Amerika Serikat", "Rusia"], correct: 3 },
        { q: "Ibu kota negara Jepang adalah...", options: ["Seoul", "Kyoto", "Osaka", "Tokyo"], correct: 3 },
        { q: "Sungai terpanjang di dunia adalah...", options: ["Amazon", "Nil", "Mekong", "Mississippi"], correct: 1 },
        { q: "Benua terkecil di dunia adalah...", options: ["Eropa", "Australia", "Afrika", "Antartika"], correct: 1 },
        { q: "Gunung tertinggi di dunia adalah...", options: ["Krakatau", "Everest", "Fuji", "Kilimanjaro"], correct: 1 },
        { q: "Garis khatulistiwa di Indonesia melewati kota...", options: ["Pontianak", "Jakarta", "Medan", "Surabaya"], correct: 0 },
        { q: "Negara yang mendapat julukan Negeri Gajah Putih adalah...", options: ["Vietnam", "Laos", "Thailand", "Kamboja"], correct: 2 },
        { q: "Samudra terluas di dunia adalah...", options: ["Samudra Hindia", "Samudra Pasifik", "Samudra Atlantik", "Samudra Arktik"], correct: 1 },
        { q: "Gurun pasir terbesar di dunia adalah...", options: ["Gobi", "Sahara", "Kalahari", "Atacama"], correct: 1 },
        { q: "Ibu kota negara Australia adalah...", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correct: 2 },
        { q: "Negara kincir angin adalah julukan untuk...", options: ["Jerman", "Belanda", "Prancis", "Denmark"], correct: 1 },
        { q: "Pulau terbesar di Indonesia adalah...", options: ["Papua", "Kalimantan", "Sumatera", "Sulawesi"], correct: 1 },
        { q: "Selat yang memisahkan pulau Jawa dan Sumatera adalah...", options: ["Selat Bali", "Selat Madura", "Selat Sunda", "Selat Makassar"], correct: 2 },
        { q: "Negara terkecil di dunia adalah...", options: ["Monako", "Vatikan", "San Marino", "Maladewa"], correct: 1 },
        { q: "Benua yang tidak memiliki penduduk asli adalah...", options: ["Australia", "Antartika", "Amerika", "Afrika"], correct: 1 },
        { q: "Pegunungan yang memisahkan Eropa dan Asia adalah...", options: ["Alpen", "Ural", "Himalaya", "Andes"], correct: 1 },
        { q: "Nama mata uang Jepang adalah...", options: ["Yuan", "Won", "Yen", "Ringgit"], correct: 2 },
        { q: "Danau terbesar di Indonesia adalah...", options: ["Danau Batur", "Danau Toba", "Danau Poso", "Danau Sentani"], correct: 1 },
        { q: "Negara manakah yang memiliki jumlah penduduk terbanyak di dunia?", options: ["India", "Tiongkok", "Indonesia", "Amerika Serikat"], correct: 0 },
        { q: "Garis bujur 0 derajat melewati kota...", options: ["London (Greenwich)", "Paris", "New York", "Jakarta"], correct: 0 },
        { q: "Ibu kota negara Perancis adalah...", options: ["Lyon", "Paris", "Marseille", "Nice"], correct: 1 },
        { q: "Air terjun tertinggi di dunia adalah...", options: ["Niagara", "Victoria", "Angel Falls", "Iguazu"], correct: 2 },
        { q: "Negara yang berbatasan darat langsung dengan Indonesia di bagian utara adalah...", options: ["Papua Nugini", "Timor Leste", "Malaysia", "Singapura"], correct: 2 },
        { q: "Benua Hitam adalah julukan untuk benua...", options: ["Eropa", "Asia", "Amerika", "Afrika"], correct: 3 },
        { q: "Negara kepulauan terbesar di dunia adalah...", options: ["Filipina", "Jepang", "Indonesia", "Maladewa"], correct: 2 },
        { q: "Provinsi paling barat di Indonesia adalah...", options: ["Riau", "Sumatera Utara", "Aceh", "Kepulauan Riau"], correct: 2 },
        { q: "Ibu kota negara Korea Selatan adalah...", options: ["Pyongyang", "Tokyo", "Seoul", "Busan"], correct: 2 },
        { q: "Gunung tertinggi di Indonesia adalah...", options: ["Gunung Semeru", "Gunung Rinjani", "Puncak Jaya", "Gunung Kerinci"], correct: 2 },
        { q: "Laut yang paling asin di dunia adalah...", options: ["Laut Merah", "Laut Mati", "Laut Hitam", "Laut Kaspia"], correct: 1 },
        { q: "Negara yang memiliki garis pantai terpanjang di dunia adalah...", options: ["Indonesia", "Kanada", "Australia", "Rusia"], correct: 1 },
        { q: "Ibu kota negara Mesir adalah...", options: ["Kairo", "Alexandria", "Luxor", "Aswan"], correct: 0 },
        { q: "Puncak tertinggi di benua Afrika adalah...", options: ["Gunung Kenya", "Gunung Kilimanjaro", "Gunung Elbrus", "Gunung Atlas"], correct: 1 },
        { q: "Negara Tirai Bambu adalah julukan untuk...", options: ["Jepang", "Korea", "Tiongkok", "Vietnam"], correct: 2 },
        { q: "Mata uang negara Thailand adalah...", options: ["Baht", "Peso", "Dong", "Riel"], correct: 0 },
        { q: "Benua yang dihuni oleh kanguru adalah...", options: ["Afrika", "Amerika", "Australia", "Asia"], correct: 2 },
        { q: "Ibu kota negara Rusia adalah...", options: ["Saint Petersburg", "Moskow", "Kazan", "Novosibirsk"], correct: 1 },
        { q: "Sungai terpanjang di Indonesia adalah...", options: ["Sungai Musi", "Sungai Barito", "Sungai Mahakam", "Sungai Kapuas"], correct: 3 },
        { q: "Negara yang terkenal dengan Menara Pisa adalah...", options: ["Spanyol", "Prancis", "Italia", "Yunani"], correct: 2 },
        { q: "Samudra terkecil di dunia adalah...", options: ["Samudra Arktik", "Samudra Hindia", "Samudra Atlantik", "Samudra Antartika"], correct: 0 },
        { q: "Ibu kota negara Inggris adalah...", options: ["London", "Manchester", "Liverpool", "Birmingham"], correct: 0 },
        { q: "Negara yang memiliki banyak pulau di Laut Aegea adalah...", options: ["Italia", "Yunani", "Turki", "Spanyol"], correct: 1 },
        { q: "Danau terdalam di dunia adalah...", options: ["Danau Toba", "Danau Victoria", "Danau Baikal", "Danau Superior"], correct: 2 },
        { q: "Kanal yang menghubungkan Samudra Atlantik dan Pasifik adalah...", options: ["Kanal Suez", "Kanal Panama", "Kanal Korintus", "Kanal Kiel"], correct: 1 },
        { q: "Ibu kota negara Brazil adalah...", options: ["Rio de Janeiro", "Sao Paulo", "Brasilia", "Salvador"], correct: 2 },
        { q: "Pulau Dewata adalah julukan untuk pulau...", options: ["Lombok", "Bali", "Nias", "Madura"], correct: 1 },
        { q: "Negara yang terletak di dua benua (Asia dan Eropa) adalah...", options: ["Rusia", "Turki", "Mesir", "Kazakhstan"], correct: 1 },
        { q: "Negara penghasil kopi terbesar di dunia adalah...", options: ["Vietnam", "Kolombia", "Brazil", "Indonesia"], correct: 2 },
        { q: "Ibu kota negara Arab Saudi adalah...", options: ["Mekkah", "Madinah", "Riyadh", "Jeddah"], correct: 2 },
        { q: "Kota yang dijuluki 'The Big Apple' adalah...", options: ["Los Angeles", "Chicago", "New York", "San Francisco"], correct: 2 },
        { q: "Negara yang memiliki bendera bergambar daun maple adalah...", options: ["Amerika Serikat", "Kanada", "Selandia Baru", "Situs"], correct: 1 }
    ],

    hiburan: [
        { q: "Siapa pemeran utama film Iron Man?", options: ["Chris Evans", "Robert Downey Jr.", "Tom Holland", "Brad Pitt"], correct: 1 },
        { q: "Genre musik yang berasal dari Jamaika adalah...", options: ["Jazz", "Rock", "Reggae", "Pop"], correct: 2 },
        { q: "Siapa penyanyi lagu 'Shape of You'?", options: ["Justin Bieber", "Ed Sheeran", "Bruno Mars", "Adele"], correct: 1 },
        { q: "Film animasi tentang ikan badut yang mencari anaknya adalah...", options: ["Shark Tale", "Finding Nemo", "Toy Story", "Cars"], correct: 1 },
        { q: "Vokalis dari band legendaris Queen adalah...", options: ["Mick Jagger", "Freddie Mercury", "John Lennon", "David Bowie"], correct: 1 },
        { q: "Penyanyi yang dijuluki 'King of Pop' adalah...", options: ["Elvis Presley", "Prince", "Michael Jackson", "Justin Timberlake"], correct: 2 },
        { q: "Alat musik petik tradisional dari NTT adalah...", options: ["Angklung", "Sasando", "Kecapi", "Kolintang"], correct: 1 },
        { q: "Siapa sutradara film 'Avatar' dan 'Titanic'?", options: ["Steven Spielberg", "Christopher Nolan", "James Cameron", "Quentin Tarantino"], correct: 2 },
        { q: "Grup K-Pop yang menyanyikan lagu 'Dynamite' adalah...", options: ["EXO", "Blackpink", "BTS", "Seventeen"], correct: 2 },
        { q: "Senjata ikonik dalam film Star Wars disebut...", options: ["Blaster", "Lightsaber", "Sonic Wand", "Power Sword"], correct: 1 },
        { q: "Siapa pemenang piala Oscar kategori Aktor Terbaik lewat film 'Joker' (2019)?", options: ["Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Christian Bale"], correct: 1 },
        { q: "Platform streaming video terbesar di dunia adalah...", options: ["Netflix", "YouTube", "Disney+", "Hulu"], correct: 1 },
        { q: "Harry Potter adalah karya dari penulis...", options: ["Roald Dahl", "J.K. Rowling", "Stephen King", "Enid Blyton"], correct: 1 },
        { q: "Lagu 'Laskar Pelangi' dinyanyikan oleh band...", options: ["Sheila on 7", "Nidji", "Peterpan", "Ungu"], correct: 1 },
        { q: "Film yang menceritakan tentang tenggelamnya kapal pesiar besar adalah...", options: ["Poseidon", "Titanic", "Deepwater Horizon", "Life of Pi"], correct: 1 },
        { q: "Siapa pencipta karakter Mickey Mouse?", options: ["Stan Lee", "Walt Disney", "Charles Schulz", "Hanna Barbera"], correct: 1 },
        { q: "Instrumen musik yang dimainkan dengan cara digesek adalah...", options: ["Gitar", "Biola", "Drum", "Seruling"], correct: 1 },
        { q: "Film horor Indonesia tentang pengabdi setan disutradarai oleh...", options: ["Hanung Bramantyo", "Joko Anwar", "Riri Riza", "Mira Lesmana"], correct: 1 },
        { q: "Superhero yang berasal dari planet Krypton adalah...", options: ["Batman", "Spiderman", "Superman", "Aquaman"], correct: 2 },
        { q: "Apa nama ajang penghargaan tertinggi untuk insan musik di dunia?", options: ["Grammy Awards", "Oscar", "Emmy Awards", "Golden Globe"], correct: 0 },
        { q: "Siapa pemeran Jack Sparrow dalam 'Pirates of the Caribbean'?", options: ["Orlando Bloom", "Johnny Depp", "Tom Cruise", "Will Smith"], correct: 1 },
        { q: "Anime tentang ninja yang ingin menjadi Hokage adalah...", options: ["One Piece", "Naruto", "Dragon Ball", "Bleach"], correct: 1 },
        { q: "Band asal Bandung yang mempopulerkan lagu 'Menghapus Jejakmu' adalah...", options: ["Noah/Peterpan", "Dewa 19", "Slank", "Padi"], correct: 0 },
        { q: "Apa judul film pertama dalam Marvel Cinematic Universe?", options: ["Captain America", "The Avengers", "Iron Man", "Thor"], correct: 2 },
        { q: "Siapa penyanyi wanita yang mempopulerkan lagu 'Hello'?", options: ["Rihanna", "Adele", "Taylor Swift", "Beyonce"], correct: 1 },
        { q: "Negara asal tarian Samba adalah...", options: ["Spanyol", "Meksiko", "Brasil", "Argentina"], correct: 2 },
        { q: "Tokoh detektif terkenal asal Inggris ciptaan Arthur Conan Doyle adalah...", options: ["Hercule Poirot", "Sherlock Holmes", "Arsene Lupin", "James Bond"], correct: 1 },
        { q: "Pemeran film 'Spider-Man: No Way Home' adalah...", options: ["Tobey Maguire", "Andrew Garfield", "Tom Holland", "Semua Benar"], correct: 3 },
        { q: "Apa instrumen musik yang identik dengan musik Jazz?", options: ["Suling", "Saksofon", "Gendang", "Ukulele"], correct: 1 },
        { q: "Siapa penyanyi Indonesia yang go international dengan lagu 'Coke Bottle'?", options: ["Agnez Mo", "Raisa", "Isyana Sarasvati", "Lyodra"], correct: 0 },
        { q: "Apa nama kerajaan dalam film 'Frozen'?", options: ["Arendelle", "Genovia", "Wakanda", "Asgard"], correct: 0 },
        { q: "Siapa juri MasterChef Indonesia yang dijuluki 'Queen of Pastry'?", options: ["Chef Renatta", "Chef Juna", "Chef Farah Quinn", "Chef Marinka"], correct: 0 },
        { q: "Apa nama perusahaan di balik film 'Toy Story'?", options: ["Dreamworks", "Pixar", "Sony Pictures", "Warner Bros"], correct: 1 },
        { q: "Lagu 'Bohemian Rhapsody' memiliki durasi sekitar...", options: ["3 menit", "6 menit", "10 menit", "2 menit"], correct: 1 },
        { q: "Artis Hollywood yang memerankan 'Wonder Woman' adalah...", options: ["Scarlett Johansson", "Gal Gadot", "Margot Robbie", "Emma Watson"], correct: 1 },
        { q: "Penyanyi yang mempopulerkan tarian 'Moonwalk' adalah...", options: ["Elvis Presley", "Michael Jackson", "Usher", "Bruno Mars"], correct: 1 },
        { q: "Film drakor yang viral tentang permainan bertahan hidup adalah...", options: ["The Glory", "Squid Game", "Kingdom", "Moving"], correct: 1 },
        { q: "Siapa pencipta lagu kebangsaan 'Indonesia Raya'?", options: ["Ibu Sud", "W.R. Supratman", "Kusbini", "Ismail Marzuki"], correct: 1 },
        { q: "Genre film yang bertujuan untuk menakut-nakuti penonton adalah...", options: ["Komedi", "Horor", "Romantis", "Dokumenter"], correct: 1 },
        { q: "Siapa penyanyi lagu 'To the Bone' yang sempat viral?", options: ["Pamungkas", "Tulus", "Ardhito Pramono", "Rizky Febian"], correct: 0 },
        { q: "Seniman terkenal yang melukis 'Mona Lisa' adalah...", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correct: 1 },
        { q: "Film 'The Lion King' menceritakan tentang seekor singa bernama...", options: ["Mufasa", "Simba", "Scar", "Timon"], correct: 1 },
        { q: "Apa nama grup musik yang digawangi oleh Ahmad Dhani?", options: ["Sheila on 7", "Dewa 19", "Slank", "Gigi"], correct: 1 },
        { q: "Aktor yang memerankan karakter 'The Rock' adalah...", options: ["Vin Diesel", "Dwayne Johnson", "Jason Statham", "John Cena"], correct: 1 },
        { q: "Penyanyi muda Amerika yang populer dengan lagu 'Bad Guy' adalah...", options: ["Billie Eilish", "Olivia Rodrigo", "Ariana Grande", "Dua Lipa"], correct: 0 },
        { q: "Serial kartun tentang spons kuning yang tinggal di laut adalah...", options: ["Patrick Star", "SpongeBob SquarePants", "Squidward", "Mr. Krabs"], correct: 1 },
        { q: "Siapa nama asli dari rapper Eminem?", options: ["Marshall Mathers", "Curtis Jackson", "Shawn Carter", "Kanye West"], correct: 0 },
        { q: "Film 'Parasite' yang memenangkan Oscar 2020 berasal dari...", options: ["Jepang", "Korea Selatan", "Thailand", "Tiongkok"], correct: 1 },
        { q: "Apa kepanjangan dari K-Pop?", options: ["Korean Popular", "Korean Pop", "Korean People", "Korea Power"], correct: 1 },
        { q: "Siapa pemeran film 'Mission Impossible' yang sering melakukan aksi berbahaya sendiri?", options: ["Brad Pitt", "Tom Cruise", "Keanu Reeves", "Liam Neeson"], correct: 1 }
    ]
};